[pytest]

# Test locations
testpaths =
            test_cases
            api/tests

# Console output
addopts = -s -v

# Test markers
markers =
        regression: regression test cases
        sanity: sanity test cases
        api: API automation test cases
        ui: UI automation test cases

# HTML report settings
log_cli = true
log_cli_level = INFO

# Python files to consider as tests
python_files =
            test_*.py